name: CI
on: [push]

jobs:
  testsuite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq restic
          sudo restic self-update
          pip install poetry
          poetry install

      - name: Testsuite
        run: |
          poetry run pytest --runslow -vv --color=yes
